name: "hell-garage"
services:
  
  api:
    container_name: api
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  database:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ./data:/var/opt/mssql/data
    env_file:
      - .env